#!/bin/bash

tsc --out temp.js --target ES5 --removeComments --suppressImplicitAnyIndexErrors Editor.ts
contents="(function($){$(< temp.js)})(jQuery);"
#contents="$(< temp.js)"
echo "$contents" > ../editor.js
rm temp.js